defaults: &defaults
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  username: root
  password:
  pool: 12

development:
  <<: *defaults
  database: quting_development

production:
  <<: *defaults
  database: quting_production

test: &test
  <<: *defaults
  database: quting_test
