require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MfilesController do

  # This should return the minimal set of attributes required to create a valid
  # Mfile. As you add validations to Mfile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "media_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MfilesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mfiles as @mfiles" do
      mfile = Mfile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mfiles).should eq([mfile])
    end
  end

  describe "GET show" do
    it "assigns the requested mfile as @mfile" do
      mfile = Mfile.create! valid_attributes
      get :show, {:id => mfile.to_param}, valid_session
      assigns(:mfile).should eq(mfile)
    end
  end

  describe "GET new" do
    it "assigns a new mfile as @mfile" do
      get :new, {}, valid_session
      assigns(:mfile).should be_a_new(Mfile)
    end
  end

  describe "GET edit" do
    it "assigns the requested mfile as @mfile" do
      mfile = Mfile.create! valid_attributes
      get :edit, {:id => mfile.to_param}, valid_session
      assigns(:mfile).should eq(mfile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mfile" do
        expect {
          post :create, {:mfile => valid_attributes}, valid_session
        }.to change(Mfile, :count).by(1)
      end

      it "assigns a newly created mfile as @mfile" do
        post :create, {:mfile => valid_attributes}, valid_session
        assigns(:mfile).should be_a(Mfile)
        assigns(:mfile).should be_persisted
      end

      it "redirects to the created mfile" do
        post :create, {:mfile => valid_attributes}, valid_session
        response.should redirect_to(Mfile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mfile as @mfile" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mfile.any_instance.stub(:save).and_return(false)
        post :create, {:mfile => { "media_id" => "invalid value" }}, valid_session
        assigns(:mfile).should be_a_new(Mfile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mfile.any_instance.stub(:save).and_return(false)
        post :create, {:mfile => { "media_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mfile" do
        mfile = Mfile.create! valid_attributes
        # Assuming there are no other mfiles in the database, this
        # specifies that the Mfile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mfile.any_instance.should_receive(:update_attributes).with({ "media_id" => "1" })
        put :update, {:id => mfile.to_param, :mfile => { "media_id" => "1" }}, valid_session
      end

      it "assigns the requested mfile as @mfile" do
        mfile = Mfile.create! valid_attributes
        put :update, {:id => mfile.to_param, :mfile => valid_attributes}, valid_session
        assigns(:mfile).should eq(mfile)
      end

      it "redirects to the mfile" do
        mfile = Mfile.create! valid_attributes
        put :update, {:id => mfile.to_param, :mfile => valid_attributes}, valid_session
        response.should redirect_to(mfile)
      end
    end

    describe "with invalid params" do
      it "assigns the mfile as @mfile" do
        mfile = Mfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => mfile.to_param, :mfile => { "media_id" => "invalid value" }}, valid_session
        assigns(:mfile).should eq(mfile)
      end

      it "re-renders the 'edit' template" do
        mfile = Mfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => mfile.to_param, :mfile => { "media_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mfile" do
      mfile = Mfile.create! valid_attributes
      expect {
        delete :destroy, {:id => mfile.to_param}, valid_session
      }.to change(Mfile, :count).by(-1)
    end

    it "redirects to the mfiles list" do
      mfile = Mfile.create! valid_attributes
      delete :destroy, {:id => mfile.to_param}, valid_session
      response.should redirect_to(mfiles_url)
    end
  end

end
